version: '3.6'

services:

  backend:
    container_name: boilermatch_backend
    build: 
        context: ./backend
    ports: 
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    
  postgres:
    container_name: postgres_db
    image: postgis/postgis
    env_file:
      - ./backend/env
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: always
    volumes:
       - pgdata:/var/lib/postgresql/data  
    networks:
      vpcbr:
    
  frontend:
    container_name: boilermatch_frontend
    build: 
        context: ./frontend
    ports: 
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend:/usr/frontend/
      - /usr/frontend/node_modules
    depends_on:
      - backend
  
 
volumes:
  pgdata:

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1    
