version: '3.1'

services:

  db:
    container_name: db_postgres_postgres
    image: postgres
    restart: always
    env_file:
      - ./env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
 
  web:
    build: .
    command: nodemon
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on: 
      - db

