version: '3.1'

services:

  web:
    container_name: boilermatch_web
    build: .
    command: nodemon
    restart: always
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
 

  postgres:
    container_name: postgres_db
    image: sameersbn/postgresql
    restart: always
    env_file:
      - ./env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
 
 